Crude initial split
Trying to use pdfium on the server (api) will raise an Error because the api ideally would not be able to use it... use a celery task intead

ModuleNotFoundError: No module named 'pypdfium2'